source 'https://rubygems.org'

# Middleman
gem 'ffi', '~>1.9.3'
gem 'middleman', '~>4.1.4'
gem 'middleman-gh-pages', '~> 0.0.3'
gem 'middleman-syntax', '~> 2.1.0'
gem 'middleman-autoprefixer', '~> 2.7.0'
gem "middleman-sprockets", "~> 4.0.0.rc"
gem 'rouge', '~> 1.10.1'
gem 'redcarpet', '~> 3.3.2'
gem "middleman-livereload", "~> 3.4.3"
